import Head from "next/head";
import { useAuth } from "../firebase/firebase";
import { useState, useLayoutEffect } from "react";
import SideBar from "../compos/SideBar";
import HomeBlogs from "../compos/HomeBlogs";
import { useStore } from "./_app";

export default function Home() {
  const [loading, setLoading] = useState(false);
  const [err, setErr] = useState(false);

  return (
    <>
      <Head>
        <title>Bloggers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <div className="">
        <div className="flex  w-screen h-screen bg-bg ">
          <SideBar  />
          <HomeBlogs />
        </div>
      </div>
    </>
  );
}
