import Head from "next/head";
import { useState, useEffect } from "react";
import SideBar from "../compos/SideBar";
import PostTab from "../compos/PostTab";
import HomeBlogs from "../compos/HomeBlogs";
export default function Home() {
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const [postTabOpen, setPostTabOpen] = useState(false);
  return (
    <>
      <Head>
        <title>Cogle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <div className="">
        <div className="flex w-screen bg-bg ">
          <SideBar
            sidebarOpen={sidebarOpen}
            setSidebarOpen={setSidebarOpen}
            setPostTabOpen={setPostTabOpen}
          />
          <HomeBlogs sidebarOpen={sidebarOpen} />
        </div>
      </div>
      {postTabOpen && <PostTab setPostTabOpen={setPostTabOpen} />}
    </>
  );
}
