import Head from "next/head";
export default function Login() {
  return (
    <section className="">
      <Head>
        <title>Sign up to bloggers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <div className="">
        <div className="">
          <div className="">
            <button className="">Log in with Google</button>
          </div>
        </div>
        <div className="">
          {/* <Image
          width="500"
          height="500" 
          src="../public/loginSVG.SVG" alt=""
           className={s.side__img} /> */}
        </div>
      </div>
    </section>
  );
}
