import Head from "next/head";
import { useGoogleLogin, GoogleLogin } from "@react-oauth/google";
export default function Login() {
  const login = useGoogleLogin({
    onSuccess: (tokenResponse) => console.log(tokenResponse),
  });
  return (
    <section className="">
      <Head>
        <title>Sign up to bloggers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <div className="">
        <div className="">
          <div className="">
            <button className="" onClick={() => login()}>
              Log in with Google
            </button>
            <GoogleLogin
              onSuccess={(credentialResponse) => {
                console.log(credentialResponse);
              }}
              onError={() => {
                console.log("Login Failed");
              }}
              useOneTap
            />
          </div>
        </div>
        <div className="">
          {/* <Image
          width="500"
          height="500" 
          src="../public/loginSVG.SVG" alt=""
           className={s.side__img} /> */}
        </div>
      </div>
    </section>
  );
}
